name: Push

on:
  push:
    branches:
      - main

jobs:
  build:
    uses: ./.github/workflows/test.yml

  publish-javadoc:
    needs: build
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
        with:
          path: source
      - name: Download JavaDoc
        uses: actions/download-artifact@v3
        with:
          name: javadoc
          path: javadoc
      - name: Checkout publish
        uses: actions/checkout@v3
        with:
          path: publish
          ref: gh-pages
      - name: Publish
        run: ./scripts/ci_scripts/publishApiDocs.sh
        working-directory: source
        env:
          GITHUB_USER: github-actions
          GITHUB_EMAIL: github-actions@github.com
          SOURCE_DIR: ${{ github.workspace }}/source
          PUBLISH_DIR: ${{ github.workspace }}/publish
          SOURCE_BRANCH: ${{ github.ref_name }}
          JAVADOC_DIR: ${{ github.workspace }}/javadoc

  publish-snapshot:
    needs: build
    name: Publish Java artifact to GitHub Packages
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: 8
          distribution: temurin
          cache: maven
          gpg-private-key: ${{ secrets.OSSRH_GPG_SECRET_KEY }}
          gpg-passphrase: MAVEN_GPG_PASSPHRASE
      - name: Publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MAVEN_GPG_PASSPHRASE: ${{ secrets.OSSRH_GPG_SECRET_KEY_PASSWORD }}
        run: ${{ github.workspace }}/.github/scripts/maven_publish_snapshot.sh
