name: "Security vulnerability scan"

on:
  schedule:
    - cron: "20 23 * * *"

jobs:
  scan:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        branch-name: ["main", "release-2.2"]
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ matrix.branch-name }}
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"
          cache: maven
      - name: Scan
        run: mvn -P owasp dependency-check:check
      - name: "Archive dependency-check report"
        uses: actions/upload-artifact@v3
        with:
          name: dependency-check-report-${{ matrix.branch-name }}
          path: target/dependency-check-report.html
