name: "Security vulnerability scan"

on:
  schedule:
    - cron: "20 23 * * 0"

jobs:
  scan:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"
          cache: maven
      - name: Scan
        env:
          NVD_API_KEY: ${{ secrets.NVD_API_KEY }}
        run: mvn -P owasp dependency-check:check
      - name: "Archive dependency-check report"
        if: success() || failure()
        uses: actions/upload-artifact@v3
        with:
          name: dependency-check-report
          path: target/dependency-check-report.html
